// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BFA.Persistence.Migrations;

[DbContext(typeof(BfaDbContext))]
[Migration("20260723020000_AddCustomerTrackingStage")]
partial class AddCustomerTrackingStage
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Target model is maintained in BfaDbContextModelSnapshot.
    }
}
