// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BFA.Persistence.Migrations
{
    [DbContext(typeof(BfaDbContext))]
    [Migration("20260722094000_AddShippingRatesAndOrderFees")]
    partial class AddShippingRatesAndOrderFees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Target model is maintained in BfaDbContextModelSnapshot after this migration is applied.
            // This stub allows the migration to be discovered and executed by MigrateAsync.
        }
    }
}
